development:
  app_id: 114653015261512
  app_context: "svetzal-auth"
  auth_path: "/fbauth"

test:
  app_id: 114653015261512
  app_context: "svetzal-auth"
  auth_path: "/fbauth"

cucumber:
  app_id: 114653015261512
  app_context: "svetzal-auth"
  auth_path: "/fbauth"

production:
  app_id: 114653015261512
  app_context: "svetzal-auth"
  auth_path: "/fbauth"
