development:
  app_id: 114653015261512
  app_context: "svetzal-auth"

test:
  app_id: 114653015261512
  app_context: "svetzal-auth"

cucumber:
  app_id: 114653015261512
  app_context: "svetzal-auth"

production:
  app_id: 114653015261512
  app_context: "svetzal-auth"
