require File.join(File.dirname(__FILE__), '..', 'lib', 'fbauth.rb')
require File.join(File.dirname(__FILE__), 'mock', 'fbauth', 'http.rb')
require File.join(File.dirname(__FILE__), 'mock', 'fbauth', 'config.rb')
require File.join(File.dirname(__FILE__), 'mock', 'fbauth', 'graph.rb')
require File.join(File.dirname(__FILE__), 'mock', 'actioncontroller_base.rb')
require File.join(File.dirname(__FILE__), 'mock', 'facebook_controller.rb')
